import {
  Shield, CheckCircle2, AlertTriangle, MapPin, Star, Heart,
  MessageCircle, User, ArrowLeft, Camera, BadgeCheck,
  ChevronRight, Info, Search, SlidersHorizontal, Verified,
  Video, Smartphone, Sparkles, Waves, Umbrella, Coffee,
  Navigation, Share2, ShieldCheck, Lock, Zap, Calendar,
  Activity, Globe, Layers,
  ArrowRight, Target, Check, Clock, Home, MessageSquare, Send,
  UserCheck, LayoutDashboard, ListTodo, Lightbulb, ExternalLink, X, Minus, Loader2,
  Bell, ShieldAlert, Key, Users, ImagePlus, LogOut,
  Award, Crown, Circle, ChevronLeft, Phone,
  FileText, FileSpreadsheet, Mail, Map, LayoutGrid
} from 'lucide-react';

export const Icons = {
  Shield,
  CheckCircle2,
  AlertTriangle,
  MapPin,
  Star,
  Heart,
  MessageCircle,
  User,
  ArrowLeft,
  Camera,
  BadgeCheck,
  ChevronRight,
  Info,
  Search,
  SlidersHorizontal,
  Verified,
  Video,
  Smartphone,
  Sparkles,
  Waves,
  Umbrella,
  Coffee,
  Navigation,
  Share2,
  ShieldCheck,
  Lock,
  Zap,
  Calendar,
  Activity,
  Globe,
  Layers,
  ArrowRight,
  Target,
  Check,
  Clock,
  Home,
  MessageSquare,
  UserCheck,
  LayoutDashboard,
  ListTodo,
  Lightbulb,
  ExternalLink,
  X,
  Minus,
  Loader2,
  Send,
  Bell,
  ShieldAlert,
  Key,
  Users,
  ImagePlus,
  LogOut,
  Award,
  Crown,
  Circle,
  ChevronLeft,
  Phone,
  FileText,
  FileSpreadsheet,
  Mail,
  Map,
  LayoutGrid
};
